
// This file is used to configure the application properties such as database connection, server port, etc.
spring.application.name=codeiris
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update